name = "Myexample"
uuid = "b9011382-2dae-4e5e-a90d-d510b72afdbe"
authors = ["Karan Beeshm <karanbeeshmrajkumar@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
